import java.lang.Integer;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vegard Rogne
 */
public class FrameAddTrack extends javax.swing.JFrame {
    private Integer integer;
    private TrackOrganizer trackOrganizer;   
    //************Music Variables***************
    private String musicTitleVar;
    private long musicMinutesVar;
    private long musicSecondsVar;
    private String musicArtistVar;
    private int musicDateVar;
    private int musicTimesPlayedVar;
    private int musicArchiveNumberVar;
    //*******************************************
   

    
    /**
     * Creates new form FrameAddTrack
     */
    public FrameAddTrack() {
        initComponents();  
        trackOrganizer = new TrackOrganizer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        musicFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        musicTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        musicMinutes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        musicSeconds = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        musicArtist = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        musicDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        musicTimesPlayed = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addMusicBtn = new javax.swing.JButton();
        musicError = new javax.swing.JLabel();
        musicArchiveNumber = new javax.swing.JTextField();
        advertisingJingleFrame = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        advertisingJingleTitle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        advertisingJingleMinutes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        advertisingJingleSeconds = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        advertisingJingleProduct = new javax.swing.JTextField();
        advertisingJingleCompany = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        addAdvertisingJingleBtn = new javax.swing.JButton();
        advertisingJingleError = new javax.swing.JLabel();
        advertisingJingleArchiveNumber = new javax.swing.JTextField();
        soundEffectsFrame = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        soundEffectsTitle = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        soundEffectsMinutes = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        soundEffectsSeconds = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        soundEffectsDescription = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        soundEffectsMediumArchiveNumber = new javax.swing.JTextField();
        addSoundEffectsBtn = new javax.swing.JButton();
        soundEffectsError = new javax.swing.JLabel();
        newsFrame = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        newsTitle = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        newsMinutes = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        newsSeconds = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        newsStory = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        newsJournalist = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        newsDateProduced = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        newsDateBoardCasted = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        newsMediumArchiveNumber = new javax.swing.JTextField();
        addNewsBtn = new javax.swing.JButton();
        newsError = new javax.swing.JLabel();
        musicBtn = new javax.swing.JButton();
        advertisingJingleBtn = new javax.swing.JButton();
        soundEffectBtn = new javax.swing.JButton();
        newsBtn = new javax.swing.JButton();

        jLabel1.setText("Title:");

        musicTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicTitleActionPerformed(evt);
            }
        });

        jLabel2.setText("Minutes:");

        musicMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicMinutesActionPerformed(evt);
            }
        });

        jLabel3.setText("Seconds:");

        musicSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicSecondsActionPerformed(evt);
            }
        });

        jLabel4.setText("Artist:");

        musicArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicArtistActionPerformed(evt);
            }
        });

        jLabel5.setText("Date:");

        musicDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicDateActionPerformed(evt);
            }
        });

        jLabel6.setText("Times Played:");

        musicTimesPlayed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicTimesPlayedActionPerformed(evt);
            }
        });

        jLabel7.setText("Medium Archive Number:");

        addMusicBtn.setText("Add Music");
        addMusicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMusicBtnActionPerformed(evt);
            }
        });

        musicArchiveNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicArchiveNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout musicFrameLayout = new javax.swing.GroupLayout(musicFrame.getContentPane());
        musicFrame.getContentPane().setLayout(musicFrameLayout);
        musicFrameLayout.setHorizontalGroup(
            musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicFrameLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(addMusicBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(musicFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(musicFrameLayout.createSequentialGroup()
                        .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6))
                        .addGap(57, 57, 57)
                        .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musicMinutes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(musicSeconds, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(musicArtist, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(musicDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(musicTimesPlayed)
                            .addComponent(musicTitle)))
                    .addGroup(musicFrameLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(musicArchiveNumber))
                    .addComponent(musicError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        musicFrameLayout.setVerticalGroup(
            musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicFrameLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(musicTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(musicMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(musicSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(musicArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(musicDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(musicTimesPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(musicArchiveNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addMusicBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musicError, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setText("Title:");

        advertisingJingleTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertisingJingleTitleActionPerformed(evt);
            }
        });

        jLabel9.setText("Minutes:");

        advertisingJingleMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertisingJingleMinutesActionPerformed(evt);
            }
        });

        jLabel10.setText("Seconds:");

        advertisingJingleSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertisingJingleSecondsActionPerformed(evt);
            }
        });

        jLabel11.setText("Product:");

        jLabel12.setText("Company:");

        advertisingJingleProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertisingJingleProductActionPerformed(evt);
            }
        });

        advertisingJingleCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertisingJingleCompanyActionPerformed(evt);
            }
        });

        jLabel13.setText("Medium Archive Number:");

        addAdvertisingJingleBtn.setText("Add Advertising Jingle");
        addAdvertisingJingleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdvertisingJingleBtnActionPerformed(evt);
            }
        });

        advertisingJingleArchiveNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertisingJingleArchiveNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout advertisingJingleFrameLayout = new javax.swing.GroupLayout(advertisingJingleFrame.getContentPane());
        advertisingJingleFrame.getContentPane().setLayout(advertisingJingleFrameLayout);
        advertisingJingleFrameLayout.setHorizontalGroup(
            advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advertisingJingleFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advertisingJingleFrameLayout.createSequentialGroup()
                        .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(advertisingJingleTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(advertisingJingleMinutes)
                            .addComponent(advertisingJingleSeconds)
                            .addComponent(advertisingJingleProduct)
                            .addComponent(advertisingJingleCompany)))
                    .addGroup(advertisingJingleFrameLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(addAdvertisingJingleBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(advertisingJingleFrameLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(advertisingJingleArchiveNumber)))
                .addContainerGap())
            .addGroup(advertisingJingleFrameLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(advertisingJingleError, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        advertisingJingleFrameLayout.setVerticalGroup(
            advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advertisingJingleFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(advertisingJingleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(advertisingJingleMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(advertisingJingleSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(advertisingJingleProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(advertisingJingleCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(advertisingJingleArchiveNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addAdvertisingJingleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(advertisingJingleError, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel14.setText("Title:");

        soundEffectsTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundEffectsTitleActionPerformed(evt);
            }
        });

        jLabel15.setText("Minutes:");

        soundEffectsMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundEffectsMinutesActionPerformed(evt);
            }
        });

        jLabel16.setText("Seconds:");

        soundEffectsSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundEffectsSecondsActionPerformed(evt);
            }
        });

        jLabel17.setText("Description:");

        soundEffectsDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundEffectsDescriptionActionPerformed(evt);
            }
        });

        jLabel18.setText("Medium Archive Number:");

        soundEffectsMediumArchiveNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundEffectsMediumArchiveNumberActionPerformed(evt);
            }
        });

        addSoundEffectsBtn.setText("Add Sound Effects");
        addSoundEffectsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSoundEffectsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout soundEffectsFrameLayout = new javax.swing.GroupLayout(soundEffectsFrame.getContentPane());
        soundEffectsFrame.getContentPane().setLayout(soundEffectsFrameLayout);
        soundEffectsFrameLayout.setHorizontalGroup(
            soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(66, 66, 66)
                                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soundEffectsDescription, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(soundEffectsSeconds, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(soundEffectsMinutes)
                                    .addComponent(soundEffectsTitle, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(soundEffectsMediumArchiveNumber))))
                    .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                        .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(soundEffectsError, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(addSoundEffectsBtn)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        soundEffectsFrameLayout.setVerticalGroup(
            soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(soundEffectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(soundEffectsMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(soundEffectsSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(soundEffectsDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(soundEffectsMediumArchiveNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSoundEffectsBtn)
                .addGap(18, 18, 18)
                .addComponent(soundEffectsError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setText("Title:");

        newsTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsTitleActionPerformed(evt);
            }
        });

        jLabel20.setText("Minutes:");

        newsMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsMinutesActionPerformed(evt);
            }
        });

        jLabel21.setText("Seconds:");

        newsSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsSecondsActionPerformed(evt);
            }
        });

        jLabel22.setText("Story:");

        newsStory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsStoryActionPerformed(evt);
            }
        });

        jLabel23.setText("Journalist:");

        newsJournalist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsJournalistActionPerformed(evt);
            }
        });

        jLabel24.setText("Date Produced:");

        newsDateProduced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsDateProducedActionPerformed(evt);
            }
        });

        jLabel25.setText("Date Boardcasted:");

        newsDateBoardCasted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsDateBoardCastedActionPerformed(evt);
            }
        });

        jLabel26.setText("Medium Archive Number:");

        newsMediumArchiveNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsMediumArchiveNumberActionPerformed(evt);
            }
        });

        addNewsBtn.setText("Add News");
        addNewsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newsFrameLayout = new javax.swing.GroupLayout(newsFrame.getContentPane());
        newsFrame.getContentPane().setLayout(newsFrameLayout);
        newsFrameLayout.setHorizontalGroup(
            newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsFrameLayout.createSequentialGroup()
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newsFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newsTitle)
                            .addComponent(newsMinutes)
                            .addComponent(newsSeconds)
                            .addComponent(newsStory)
                            .addComponent(newsJournalist)
                            .addComponent(newsDateProduced)
                            .addComponent(newsDateBoardCasted)
                            .addComponent(newsMediumArchiveNumber)))
                    .addGroup(newsFrameLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(addNewsBtn)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(newsFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newsError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        newsFrameLayout.setVerticalGroup(
            newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsFrameLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(newsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(newsMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(newsSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(newsStory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(newsJournalist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(newsDateProduced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(newsDateBoardCasted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newsMediumArchiveNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addNewsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newsError, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        musicBtn.setText("Add Music");
        musicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicBtnActionPerformed(evt);
            }
        });

        advertisingJingleBtn.setText("Add Advertising Jingle");

        soundEffectBtn.setText("Add Sound Effects");

        newsBtn.setText("Add News");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(soundEffectBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(musicBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(advertisingJingleBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(musicBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(advertisingJingleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(soundEffectBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newsBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Music Add Button.
     * @param evt 
     */
    private void addMusicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMusicBtnActionPerformed
        // TODO add your handling code here:
        boolean titleReady = true;
        if(musicTitle.getText().isEmpty())
        {
            musicError.setText("Error in Title Field!");
            titleReady = false;
        }
        boolean minutesReady = true;
        if(musicMinutes.getText().isEmpty())
        {
            musicError.setText("Error in Minutes Field!");
            minutesReady = false;
        }
        boolean secondsReady = true;
        if(musicSeconds.getText().isEmpty())
        {
            musicError.setText("Error in Seconds Field!");
            secondsReady = false;
        }
        boolean artistReady = true;
        if(musicArtist.getText().isEmpty())
        {
            musicError.setText("Error in Artist Field!");
            artistReady = false;
        }
        boolean dateReady = true;
        if(musicDate.getText().isEmpty())
        {
            musicError.setText("Error in Date Field!");
            dateReady = false;
        }
        boolean timesPlayedReady = true;
        if(musicTimesPlayed.getText().isEmpty())
        {
            musicError.setText("Error in Times Played Field!");
            timesPlayedReady = false;
        }
        boolean mediumArchiveNumber = true;
        if(musicArchiveNumber.getText().isEmpty())
        {
            musicError.setText("Error in Medium Archive Number Field!");
            mediumArchiveNumber = false;
        }
        if((titleReady)&&                   //Checks if input from title field is valid.
                (minutesReady)&&            //Checks if input from Minutes field is valid.
                 (secondsReady)&&           //Checks if input from Seconds field is valid.
                  (artistReady)&&           //Checks if input from Artist field is valid.
                   (dateReady)&&            //Checks if input from Date field is valid.
                    (timesPlayedReady)&&    //Checks if input from Times Played field is valid.
                     (mediumArchiveNumber)) //Checks if input from title Archive Number is valid.
        {
            trackOrganizer.addMusicTrack(musicTitleVar, musicMinutesVar, musicSecondsVar, musicArtistVar, musicDateVar, musicTimesPlayedVar, musicArchiveNumberVar);
            musicError.setText("Music Track Added!" + " Title: " + musicTitle.getText()
                            +" Artist: " + musicArtist.getText());
            musicTitle.setText(null);
            musicMinutes.setText(null);
            musicSeconds.setText(null);
            musicArtist.setText(null);
            musicDate.setText(null);
            musicTimesPlayed.setText(null);
            musicArchiveNumber.setText(null);         
        }
    }//GEN-LAST:event_addMusicBtnActionPerformed

    /**
     * Music Archive Number Field.
     * @param evt 
     */
    private void musicArchiveNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicArchiveNumberActionPerformed
        // TODO add your handling code here:
        try{
        String tempString = musicArchiveNumber.getText();
        int tempInt = integer.parseInt(tempString);
        musicArchiveNumberVar = tempInt;
        }
        catch(NumberFormatException e)
        {
            musicError.setText("Error in Archive Number Error!");
        }
    }//GEN-LAST:event_musicArchiveNumberActionPerformed

    /**
     * Music Times Played Field.
     * @param evt 
     */
    private void musicTimesPlayedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicTimesPlayedActionPerformed
        // TODO add your handling code here:
        try{
        String tempString = musicTimesPlayed.getText();
        int tempInt = integer.parseInt(tempString);
        musicTimesPlayedVar = tempInt;
        }
        catch(NumberFormatException e)
        {
            musicError.setText("Error in Timed Played Field!");
        }
    }//GEN-LAST:event_musicTimesPlayedActionPerformed

    /**
     * Music Date Field.
     * @param evt 
     */
    private void musicDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicDateActionPerformed
        // TODO add your handling code here:
        try{
        String tempString = musicDate.getText();
        int tempInt = integer.parseInt(tempString);
        musicDateVar = tempInt;
        }
        catch(NumberFormatException e)
        {
            musicError.setText("Error in Date Field!");
        }
    }//GEN-LAST:event_musicDateActionPerformed

    /**
     * Music Artist Field.
     * @param evt 
     */
    private void musicArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicArtistActionPerformed
        // TODO add your handling code here:
        this.musicArtistVar = musicArtist.getText();
    }//GEN-LAST:event_musicArtistActionPerformed

    /**
     * Music Seconds Field.
     * @param evt 
     */
    private void musicSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicSecondsActionPerformed
        // TODO add your handling code here:
        try{
        String tempString = musicSeconds.getText();
        int tempInt = integer.parseInt(tempString);
        musicSecondsVar = tempInt;
        }
        catch(NumberFormatException e)
        {
            musicError.setText("Error in seconds Field!");
        }
        
    }//GEN-LAST:event_musicSecondsActionPerformed

    /**
     * Music Minutes Field.
     * @param evt 
     */
    private void musicMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicMinutesActionPerformed
        // TODO add your handling code here:
        try{
        String tempString = musicMinutes.getText();
        int tempInt = integer.parseInt(tempString);
        musicMinutesVar = tempInt;
        }
        catch(NumberFormatException e)
        {
            musicError.setText("Error in Minutes Field!");
        }
             
    }//GEN-LAST:event_musicMinutesActionPerformed

    /**
     * Music Title Field.
     * @param evt 
     */
    private void musicTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicTitleActionPerformed
        // TODO add your handling code here:
        this.musicTitleVar = musicTitle.getText();
    }//GEN-LAST:event_musicTitleActionPerformed

    /**
     * AdvertisingJingle Title Field.
     * @param evt 
     */
    private void advertisingJingleTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertisingJingleTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advertisingJingleTitleActionPerformed

    /**
     * AdvertisingJingle Minutes Field.
     * @param evt 
     */
    private void advertisingJingleMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertisingJingleMinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advertisingJingleMinutesActionPerformed

    /**
     * AdvertisingJingle Seconds Field.
     * @param evt 
     */
    private void advertisingJingleSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertisingJingleSecondsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advertisingJingleSecondsActionPerformed

    /**
     * AdvertisingJingle Product Field.
     * @param evt 
     */
    private void advertisingJingleProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertisingJingleProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advertisingJingleProductActionPerformed

    /**
     * AdvertisingJingle Company Field.
     * @param evt 
     */
    private void advertisingJingleCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertisingJingleCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advertisingJingleCompanyActionPerformed

    /**
     * AdvertisingJingle Archive Number Field.
     * @param evt 
     */
    private void advertisingJingleArchiveNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertisingJingleArchiveNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advertisingJingleArchiveNumberActionPerformed

    /**
     * AdvertisingJingle Add AdvertisingJingle Button.
     * @param evt 
     */
    private void addAdvertisingJingleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdvertisingJingleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAdvertisingJingleBtnActionPerformed

    /**
     * SoundEffects Description Field.
     * 
     * @param evt 
     */
    private void soundEffectsDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundEffectsDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundEffectsDescriptionActionPerformed

    /**
     * SoundsEffects Add soundEffects Button.
     * @param evt 
     */
    private void addSoundEffectsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSoundEffectsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSoundEffectsBtnActionPerformed

    /**
     * SoundEffects Medium Archive Number Field.
     * @param evt 
     */
    private void soundEffectsMediumArchiveNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundEffectsMediumArchiveNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundEffectsMediumArchiveNumberActionPerformed

    /**
     * SoundEffects Seconds Field.
     * @param evt 
     */
    private void soundEffectsSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundEffectsSecondsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundEffectsSecondsActionPerformed

    /**
     * SoundEffect Minutes Field.
     * @param evt 
     */
    private void soundEffectsMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundEffectsMinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundEffectsMinutesActionPerformed

    /**
     * SoundEffect Title Field.
     * @param evt 
     */
    private void soundEffectsTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundEffectsTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundEffectsTitleActionPerformed

    /**
     * News Add News Button.
     * @param evt 
     */
    private void addNewsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewsBtnActionPerformed

    /**
     * News Medium Archive Number Field.
     * @param evt 
     */
    private void newsMediumArchiveNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsMediumArchiveNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsMediumArchiveNumberActionPerformed

    /**
     * News Date Boardcasted Field.
     * @param evt 
     */
    private void newsDateBoardCastedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsDateBoardCastedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsDateBoardCastedActionPerformed

    /**
     * News Date Produced Field.
     * @param evt 
     */
    private void newsDateProducedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsDateProducedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsDateProducedActionPerformed

    /**
     * News Journalist Field.
     * @param evt 
     */
    private void newsJournalistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsJournalistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsJournalistActionPerformed

    /**
     * News Story Field.
     * @param evt 
     */
    private void newsStoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsStoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsStoryActionPerformed

    /**
     * News Seconds Field.
     * @param evt 
     */
    private void newsSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsSecondsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsSecondsActionPerformed

    /**
     * News Minutes Field.
     * @param evt 
     */
    private void newsMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsMinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsMinutesActionPerformed

    /**
     * News Title Field.
     * @param evt 
     */
    private void newsTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsTitleActionPerformed

    private void musicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicBtnActionPerformed
        // TODO add your handling code here:
        musicFrame.setVisible(true);
        musicFrame.setSize(250, 450);
    }//GEN-LAST:event_musicBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAddTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAddTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAddTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAddTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAddTrack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdvertisingJingleBtn;
    private javax.swing.JButton addMusicBtn;
    private javax.swing.JButton addNewsBtn;
    private javax.swing.JButton addSoundEffectsBtn;
    private javax.swing.JTextField advertisingJingleArchiveNumber;
    private javax.swing.JButton advertisingJingleBtn;
    private javax.swing.JTextField advertisingJingleCompany;
    private javax.swing.JLabel advertisingJingleError;
    private javax.swing.JFrame advertisingJingleFrame;
    private javax.swing.JTextField advertisingJingleMinutes;
    private javax.swing.JTextField advertisingJingleProduct;
    private javax.swing.JTextField advertisingJingleSeconds;
    private javax.swing.JTextField advertisingJingleTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField musicArchiveNumber;
    private javax.swing.JTextField musicArtist;
    private javax.swing.JButton musicBtn;
    private javax.swing.JTextField musicDate;
    private javax.swing.JLabel musicError;
    private javax.swing.JFrame musicFrame;
    private javax.swing.JTextField musicMinutes;
    private javax.swing.JTextField musicSeconds;
    private javax.swing.JTextField musicTimesPlayed;
    private javax.swing.JTextField musicTitle;
    private javax.swing.JButton newsBtn;
    private javax.swing.JTextField newsDateBoardCasted;
    private javax.swing.JTextField newsDateProduced;
    private javax.swing.JLabel newsError;
    private javax.swing.JFrame newsFrame;
    private javax.swing.JTextField newsJournalist;
    private javax.swing.JTextField newsMediumArchiveNumber;
    private javax.swing.JTextField newsMinutes;
    private javax.swing.JTextField newsSeconds;
    private javax.swing.JTextField newsStory;
    private javax.swing.JTextField newsTitle;
    private javax.swing.JButton soundEffectBtn;
    private javax.swing.JTextField soundEffectsDescription;
    private javax.swing.JLabel soundEffectsError;
    private javax.swing.JFrame soundEffectsFrame;
    private javax.swing.JTextField soundEffectsMediumArchiveNumber;
    private javax.swing.JTextField soundEffectsMinutes;
    private javax.swing.JTextField soundEffectsSeconds;
    private javax.swing.JTextField soundEffectsTitle;
    // End of variables declaration//GEN-END:variables
}
