import java.lang.Integer;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vegard Rogne
 */
public class FrameAddTrack extends javax.swing.JFrame {
    private Integer integer;
    private TrackOrganizer trackOrganizer;   
    //************Music Variables***************
    private String musicTitleVar;
    private long musicMinutesVar;
    private long musicSecondsVar;
    private String musicArtistVar;
    private int musicDateVar;
    private int musicTimesPlayedVar;
    private int musicArchiveNumberVar;
    private boolean musicMediumReady = true;
    private boolean musicMinutesReady;
    private boolean musicSecondsReady;
    private boolean musicTimedPlayedReady;
    private boolean musicDateReady;
    //*******************************************
   //*************AdvertisingJingle Variables*****
    private String advertJingleTitleVar;
    private long advertJingleMinutesVar;
    private long advertJingleSecondsVar;
    private int advertJingleArchiveNumberVar;
    private String advertJingleProductVar;
    private String advertJingleCompanyVar;
    private boolean advertJingleSecondsReady;
    private boolean advertJingleMinutesReady;
    //*******************************************
    //**********SoundEffects Variables***********
    private String soundsEffectsTitleVar;
    private int soundEffectsMinutesVar;
    private int soundEffectsSecondsVar;
    private String soundEffectsDescriptionVar;
    private int soundEffectsArchiveNumberVar;
    private boolean soundEffectsSecondsReady;
    private boolean soundEffectsMinutesReady;
    //*******************************************
    //***********News Variables******************
    private boolean newsMinutesReady;
    private int newsMinutesVar;
    private boolean newsSecondsReady;
    private int newsSecondsVar;
    private int newsArchiveNumberVar;
    private boolean newsDateProducedReady;
    private int newsDateProducedVar;
    private boolean newsDateBoardcastedReady;
    private int newsDateBoardcastedVar;
    //******************************************

    
    /**
     * Creates new form FrameAddTrack
     */
    public FrameAddTrack() {
        initComponents();  
        trackOrganizer = new TrackOrganizer();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        musicFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        musicTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        musicMinutes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        musicSeconds = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        musicArtist = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        musicDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        musicTimesPlayed = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addMusicBtn = new javax.swing.JButton();
        musicError = new javax.swing.JLabel();
        musicArchiveNumber = new javax.swing.JTextField();
        advertisingJingleFrame = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        advertJingleTitle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        advertJingleMinutes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        advertJingleSeconds = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        advertJingleProduct = new javax.swing.JTextField();
        advertJingleCompany = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        addAdvertJingleBtn = new javax.swing.JButton();
        advertJingleError = new javax.swing.JLabel();
        advertJingleArchiveNumber = new javax.swing.JTextField();
        soundEffectsFrame = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        soundEffectsTitle = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        soundEffectsMinutes = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        soundEffectsSeconds = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        soundEffectsDescription = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        soundEffectsArchiveNumber = new javax.swing.JTextField();
        addSoundEffectsBtn = new javax.swing.JButton();
        soundEffectsError = new javax.swing.JLabel();
        newsFrame = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        newsTitle = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        newsMinutes = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        newsSeconds = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        newsStory = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        newsJournalist = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        newsDateProduced = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        newsDateBoardcasted = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        newsArchiveNumber = new javax.swing.JTextField();
        addNewsBtn = new javax.swing.JButton();
        newsError = new javax.swing.JLabel();
        musicBtn = new javax.swing.JButton();
        advertisingJingleBtn = new javax.swing.JButton();
        soundEffectBtn = new javax.swing.JButton();
        newsBtn = new javax.swing.JButton();

        jLabel1.setText("Title:");

        musicTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicTitleActionPerformed(evt);
            }
        });

        jLabel2.setText("Minutes:");

        musicMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicMinutesActionPerformed(evt);
            }
        });
        musicMinutes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                musicMinutesKeyReleased(evt);
            }
        });

        jLabel3.setText("Seconds:");

        musicSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicSecondsActionPerformed(evt);
            }
        });
        musicSeconds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                musicSecondsKeyReleased(evt);
            }
        });

        jLabel4.setText("Artist:");

        musicArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicArtistActionPerformed(evt);
            }
        });

        jLabel5.setText("Date:");

        musicDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicDateActionPerformed(evt);
            }
        });
        musicDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                musicDateKeyReleased(evt);
            }
        });

        jLabel6.setText("Times Played:");

        musicTimesPlayed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                musicTimesPlayedKeyReleased(evt);
            }
        });

        jLabel7.setText("Medium Archive Number:");

        addMusicBtn.setText("Add Music");
        addMusicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMusicBtnActionPerformed(evt);
            }
        });

        musicArchiveNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicArchiveNumberActionPerformed(evt);
            }
        });
        musicArchiveNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                musicArchiveNumberKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout musicFrameLayout = new javax.swing.GroupLayout(musicFrame.getContentPane());
        musicFrame.getContentPane().setLayout(musicFrameLayout);
        musicFrameLayout.setHorizontalGroup(
            musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicFrameLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(addMusicBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(musicFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(musicFrameLayout.createSequentialGroup()
                        .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6))
                        .addGap(57, 57, 57)
                        .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musicMinutes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(musicSeconds, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(musicArtist, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(musicDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(musicTimesPlayed)
                            .addComponent(musicTitle)))
                    .addGroup(musicFrameLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(musicArchiveNumber))
                    .addComponent(musicError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        musicFrameLayout.setVerticalGroup(
            musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicFrameLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(musicTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(musicMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(musicSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(musicArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(musicDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(musicTimesPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(musicFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(musicArchiveNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addMusicBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musicError, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setText("Title:");

        advertJingleTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertJingleTitleActionPerformed(evt);
            }
        });

        jLabel9.setText("Minutes:");

        advertJingleMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertJingleMinutesActionPerformed(evt);
            }
        });
        advertJingleMinutes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                advertJingleMinutesKeyReleased(evt);
            }
        });

        jLabel10.setText("Seconds:");

        advertJingleSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertJingleSecondsActionPerformed(evt);
            }
        });
        advertJingleSeconds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                advertJingleSecondsKeyReleased(evt);
            }
        });

        jLabel11.setText("Product:");

        jLabel12.setText("Company:");

        advertJingleProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertJingleProductActionPerformed(evt);
            }
        });

        advertJingleCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertJingleCompanyActionPerformed(evt);
            }
        });

        jLabel13.setText("Medium Archive Number:");

        addAdvertJingleBtn.setText("Add Advertising Jingle");
        addAdvertJingleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdvertJingleBtnActionPerformed(evt);
            }
        });

        advertJingleArchiveNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertJingleArchiveNumberActionPerformed(evt);
            }
        });
        advertJingleArchiveNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                advertJingleArchiveNumberKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout advertisingJingleFrameLayout = new javax.swing.GroupLayout(advertisingJingleFrame.getContentPane());
        advertisingJingleFrame.getContentPane().setLayout(advertisingJingleFrameLayout);
        advertisingJingleFrameLayout.setHorizontalGroup(
            advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advertisingJingleFrameLayout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(addAdvertJingleBtn)
                .addGap(57, 57, 57))
            .addGroup(advertisingJingleFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(advertJingleError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advertisingJingleFrameLayout.createSequentialGroup()
                        .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(advertJingleArchiveNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(advertJingleCompany)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advertisingJingleFrameLayout.createSequentialGroup()
                        .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(98, 98, 98)
                        .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(advertJingleProduct)
                            .addComponent(advertJingleSeconds)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advertisingJingleFrameLayout.createSequentialGroup()
                        .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(101, 101, 101)
                        .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(advertJingleMinutes)
                            .addComponent(advertJingleTitle))))
                .addContainerGap())
        );
        advertisingJingleFrameLayout.setVerticalGroup(
            advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advertisingJingleFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(advertJingleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(advertJingleMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(advertJingleSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(advertJingleProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(advertJingleCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(advertisingJingleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(advertJingleArchiveNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addAdvertJingleBtn)
                .addGap(18, 18, 18)
                .addComponent(advertJingleError, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel14.setText("Title:");

        soundEffectsTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundEffectsTitleActionPerformed(evt);
            }
        });

        jLabel15.setText("Minutes:");

        soundEffectsMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundEffectsMinutesActionPerformed(evt);
            }
        });
        soundEffectsMinutes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soundEffectsMinutesKeyReleased(evt);
            }
        });

        jLabel16.setText("Seconds:");

        soundEffectsSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundEffectsSecondsActionPerformed(evt);
            }
        });
        soundEffectsSeconds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soundEffectsSecondsKeyReleased(evt);
            }
        });

        jLabel17.setText("Description:");

        soundEffectsDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundEffectsDescriptionActionPerformed(evt);
            }
        });

        jLabel18.setText("Medium Archive Number:");

        soundEffectsArchiveNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundEffectsArchiveNumberActionPerformed(evt);
            }
        });
        soundEffectsArchiveNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soundEffectsArchiveNumberKeyReleased(evt);
            }
        });

        addSoundEffectsBtn.setText("Add Sound Effects");
        addSoundEffectsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSoundEffectsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout soundEffectsFrameLayout = new javax.swing.GroupLayout(soundEffectsFrame.getContentPane());
        soundEffectsFrame.getContentPane().setLayout(soundEffectsFrameLayout);
        soundEffectsFrameLayout.setHorizontalGroup(
            soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(66, 66, 66)
                                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soundEffectsDescription, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(soundEffectsSeconds, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(soundEffectsMinutes)
                                    .addComponent(soundEffectsTitle, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(soundEffectsArchiveNumber))))
                    .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                        .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(soundEffectsError, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(addSoundEffectsBtn)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        soundEffectsFrameLayout.setVerticalGroup(
            soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soundEffectsFrameLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(soundEffectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(soundEffectsMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(soundEffectsSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(soundEffectsDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(soundEffectsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(soundEffectsArchiveNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSoundEffectsBtn)
                .addGap(18, 18, 18)
                .addComponent(soundEffectsError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setText("Title:");

        newsTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsTitleActionPerformed(evt);
            }
        });

        jLabel20.setText("Minutes:");

        newsMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsMinutesActionPerformed(evt);
            }
        });
        newsMinutes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newsMinutesKeyReleased(evt);
            }
        });

        jLabel21.setText("Seconds:");

        newsSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsSecondsActionPerformed(evt);
            }
        });
        newsSeconds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newsSecondsKeyReleased(evt);
            }
        });

        jLabel22.setText("Story:");

        newsStory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsStoryActionPerformed(evt);
            }
        });

        jLabel23.setText("Journalist:");

        newsJournalist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsJournalistActionPerformed(evt);
            }
        });

        jLabel24.setText("Date Produced:");

        newsDateProduced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsDateProducedActionPerformed(evt);
            }
        });
        newsDateProduced.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newsDateProducedKeyReleased(evt);
            }
        });

        jLabel25.setText("Date Boardcasted:");

        newsDateBoardcasted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsDateBoardcastedActionPerformed(evt);
            }
        });
        newsDateBoardcasted.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newsDateBoardcastedKeyReleased(evt);
            }
        });

        jLabel26.setText("Medium Archive Number:");

        newsArchiveNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsArchiveNumberActionPerformed(evt);
            }
        });
        newsArchiveNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newsArchiveNumberKeyReleased(evt);
            }
        });

        addNewsBtn.setText("Add News");
        addNewsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newsFrameLayout = new javax.swing.GroupLayout(newsFrame.getContentPane());
        newsFrame.getContentPane().setLayout(newsFrameLayout);
        newsFrameLayout.setHorizontalGroup(
            newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsFrameLayout.createSequentialGroup()
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newsFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newsTitle)
                            .addComponent(newsMinutes)
                            .addComponent(newsSeconds)
                            .addComponent(newsStory)
                            .addComponent(newsJournalist)
                            .addComponent(newsDateProduced)
                            .addComponent(newsDateBoardcasted)
                            .addComponent(newsArchiveNumber)))
                    .addGroup(newsFrameLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(addNewsBtn)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(newsFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newsError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        newsFrameLayout.setVerticalGroup(
            newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsFrameLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(newsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(newsMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(newsSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(newsStory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(newsJournalist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(newsDateProduced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(newsDateBoardcasted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newsArchiveNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addNewsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newsError, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        musicBtn.setText("Add Music");
        musicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicBtnActionPerformed(evt);
            }
        });

        advertisingJingleBtn.setText("Add Advertising Jingle");
        advertisingJingleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertisingJingleBtnActionPerformed(evt);
            }
        });

        soundEffectBtn.setText("Add Sound Effects");
        soundEffectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundEffectBtnActionPerformed(evt);
            }
        });

        newsBtn.setText("Add News");
        newsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(soundEffectBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(musicBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(advertisingJingleBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(musicBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(advertisingJingleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(soundEffectBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newsBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Music Add Button.
     * @param evt 
     */
    private void addMusicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMusicBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Title: " + musicTitle.getText());
        System.out.println("Minutt:" + musicMinutesVar);
        System.out.println("Sek: " + musicSecondsVar);
        System.out.println("Artist: " + musicArtist.getText());
        System.out.println("Date: " + musicDateVar);
        System.out.println("Times Played: " + musicTimesPlayedVar);
        System.out.println("Archive Number: " + musicArchiveNumberVar);
        this.musicMediumReady = true;
        boolean titleReady = true;
        if(musicTitle.getText().isEmpty())
        {
            musicError.setText("Error in Title Field!");
            titleReady = false;
        }
        boolean minutesReady = true;
        if(musicMinutes.getText().isEmpty())
        {
            musicError.setText("Error in Minutes Field!");
            minutesReady = false;
        }
        boolean secondsReady = true;
        if(musicSeconds.getText().isEmpty())
        {
            musicError.setText("Error in Seconds Field!");
            secondsReady = false;
        }
        boolean artistReady = true;
        if(musicArtist.getText().isEmpty())
        {
            musicError.setText("Error in Artist Field!");
            artistReady = false;
        }
        boolean dateReady = true;
        if(musicDate.getText().isEmpty())
        {
            musicError.setText("Error in Date Field!");
            dateReady = false;
        }
        boolean timesPlayedReady = true;
        if(musicTimesPlayed.getText().isEmpty())
        {
            musicError.setText("Error in Times Played Field!");
            timesPlayedReady = false;
        }
        boolean mediumArchiveNumber = true;
        if(musicArchiveNumber.getText().isEmpty())
        {
            musicError.setText("Error in Medium Archive Number Field!");
            mediumArchiveNumber = false;
        }
        if(trackOrganizer.getMediaAt(musicArchiveNumberVar) == null)
        {
            this.musicMediumReady = false;
        }
        
        if(!this.musicMinutesReady)
        {
            musicError.setText("Wrong Input In Minutes Field!");
        }
        if(!this.musicSecondsReady)
        {
            musicError.setText("Wrong Input In Seconds Field!");
        }
        if(!this.musicTimedPlayedReady)
        {
            musicError.setText("Wrong Input In Times Played Field!");
        }
        if(!this.musicDateReady)
        {
            musicError.setText("Wrong Input In Date Field!");
        }
            
        
        
        if((titleReady)&&                   //Checks if input from title field is valid.
                (minutesReady)&&            //Checks if input from Minutes field is valid.
                 (secondsReady)&&           //Checks if input from Seconds field is valid.
                  (artistReady)&&           //Checks if input from Artist field is valid.
                   (dateReady)&&            //Checks if input from Date field is valid.
                    (timesPlayedReady)&&    //Checks if input from Times Played field is valid.
                     (mediumArchiveNumber)&&//Checks if input from archive number is valid.
                        (musicMediumReady)&& //Checks if there are any mediums with that archive number.
                          (this.musicMinutesReady)&&
                            (this.musicSecondsReady)&&
                              (this.musicTimedPlayedReady)&&
                                (this.musicDateReady))
                
                
            {
            trackOrganizer.addMusicTrack(musicTitle.getText(), musicMinutesVar, musicSecondsVar, musicArtist.getText(), musicDateVar, musicTimesPlayedVar, musicArchiveNumberVar);
            musicError.setText("Music Track Added!" + " Title: " + musicTitle.getText()
                            +" Artist: " + musicArtist.getText());
            musicTitle.setText(null);
            musicMinutes.setText(null);
            musicSeconds.setText(null);
            musicArtist.setText(null);
            musicDate.setText(null);
            musicTimesPlayed.setText(null);
            musicArchiveNumber.setText(null);         
        }
    }//GEN-LAST:event_addMusicBtnActionPerformed

    /**
     * Music Date Field.
     * @param evt 
     */
    private void musicDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicDateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_musicDateActionPerformed

    /**
     * Music Artist Field.
     * @param evt 
     */
    private void musicArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicArtistActionPerformed
        // TODO add your handling code here:
        this.musicArtistVar = musicArtist.getText();
    }//GEN-LAST:event_musicArtistActionPerformed

    /**
     * Music Seconds Field.
     * @param evt 
     */
    private void musicSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicSecondsActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_musicSecondsActionPerformed

    /**
     * Music Title Field.
     * @param evt 
     */
    private void musicTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicTitleActionPerformed
        // TODO add your handling code here:
        this.musicTitleVar = musicTitle.getText();
    }//GEN-LAST:event_musicTitleActionPerformed

    /**
     * AdvertisingJingle Title Field.
     * @param evt 
     */
    private void advertJingleTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertJingleTitleActionPerformed
        // TODO add your handling code here:
        this.advertJingleTitleVar = advertJingleTitle.getText();
    }//GEN-LAST:event_advertJingleTitleActionPerformed

    /**
     * AdvertisingJingle Minutes Field.
     * @param evt 
     */
    private void advertJingleMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertJingleMinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advertJingleMinutesActionPerformed

    /**
     * AdvertisingJingle Seconds Field.
     * @param evt 
     */
    private void advertJingleSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertJingleSecondsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advertJingleSecondsActionPerformed

    /**
     * AdvertisingJingle Product Field.
     * @param evt 
     */
    private void advertJingleProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertJingleProductActionPerformed
        // TODO add your handling code here:
        this.advertJingleProductVar = advertJingleProduct.getText();
    }//GEN-LAST:event_advertJingleProductActionPerformed

    /**
     * AdvertisingJingle Company Field.
     * @param evt 
     */
    private void advertJingleCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertJingleCompanyActionPerformed
        // TODO add your handling code here:
        this.advertJingleCompanyVar = advertJingleCompany.getText();
    }//GEN-LAST:event_advertJingleCompanyActionPerformed

    /**
     * AdvertisingJingle Archive Number Field.
     * @param evt 
     */
    private void advertJingleArchiveNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertJingleArchiveNumberActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_advertJingleArchiveNumberActionPerformed

    /**
     * AdvertisingJingle Add AdvertisingJingle Button.
     * @param evt 
     */
    private void addAdvertJingleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdvertJingleBtnActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Title: " + advertJingleTitle.getText());
        System.out.println("Minutes: " + advertJingleMinutesVar );
        System.out.println("Seconds: " + advertJingleSecondsVar);
        System.out.println("Product: " + advertJingleProduct.getText());
        System.out.println("Company: " + advertJingleCompany.getText());
        System.out.println("Archive Number: " + advertJingleArchiveNumberVar);
        if(!this.advertJingleMinutesReady)
        {
            advertJingleError.setText("Wrong Input In Minutes Field!");
        }
        if(!this.advertJingleSecondsReady)
        {
            advertJingleError.setText("Wrong Input In Seconds Field!");
        }
        
            boolean titleReady = true;
            if(advertJingleTitle.getText().isEmpty())
            {
                advertJingleError.setText("Error In Title Field!");
                titleReady = false;
            }
            
            boolean minutesReady = true;
            if(advertJingleMinutes.getText().isEmpty())
            {
                advertJingleError.setText("Error In Minutes Field!");
                minutesReady = false;
            }
            
            boolean secondsReady = true;
            if(advertJingleSeconds.getText().isEmpty())
            {
                advertJingleError.setText("Error in Seconds Field!");
                secondsReady = false;
            }
            
            boolean productReady = true;
            if(advertJingleProduct.getText().isEmpty())
            {
                advertJingleError.setText("Error in Product Field!");
                productReady = false;
            }
            boolean companyReady = true;
            if(advertJingleCompany.getText().isEmpty())
            {
                advertJingleError.setText("Error in Company Field!");
                companyReady = false;
            }
            boolean archiveNumberReady = true;
            if(advertJingleArchiveNumber.getText().isEmpty())
            {
                advertJingleError.setText("Error in Archive Number Field!");
                archiveNumberReady = false;
            }
            
            if((titleReady)&&
                    (minutesReady)&&
                     (secondsReady)&&
                      (productReady)&&
                       (companyReady)&&
                         (archiveNumberReady)&&
                          (this.advertJingleSecondsReady)&&
                            (this.advertJingleMinutesReady))
            {
                trackOrganizer.addAvertisingJingle(advertJingleTitle.getText(), advertJingleMinutesVar, advertJingleSecondsVar, advertJingleArchiveNumberVar, advertJingleProduct.getText(), advertJingleCompany.getText());
                advertJingleError.setText("Advertising Jingle Added!" + " Title: " + advertJingleTitle.getText());
            advertJingleTitle.setText(null);
            advertJingleMinutes.setText(null);
            advertJingleSeconds.setText(null);            
            advertJingleProduct.setText(null);
            advertJingleCompany.setText(null);
            advertJingleArchiveNumber.setText(null);    
            }
        
    }//GEN-LAST:event_addAdvertJingleBtnActionPerformed

    /**
     * SoundEffects Description Field.
     * 
     * @param evt 
     */
    private void soundEffectsDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundEffectsDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundEffectsDescriptionActionPerformed

    /**
     * SoundsEffects Add soundEffects Button.
     * @param evt 
     */
    private void addSoundEffectsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSoundEffectsBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Title: "+ soundEffectsTitle.getText());
        System.out.println("Minutes: " + soundEffectsMinutesVar);
        System.out.println("Seconds: " + soundEffectsSecondsVar); 
        System.out.println("Description: " + soundEffectsDescription.getText());
        System.out.println("Archive Number: " + soundEffectsArchiveNumberVar);
        boolean titleReady = true;
        if(soundEffectsTitle.getText().isEmpty())
        {
            titleReady = false;
            soundEffectsError.setText("Error in Title Field!");
        }
        boolean descriptionReady = true;
        if(soundEffectsDescription.getText().isEmpty())
        {
            descriptionReady = false;
            soundEffectsError.setText("Error In Descripion Field!");
        }
        boolean archiveNumberReady = true;
        if(soundEffectsArchiveNumber.getText().isEmpty())
        {
            archiveNumberReady = false;
            soundEffectsError.setText("Error in Archive Number Field!");
        }
        if(!this.soundEffectsMinutesReady)
        {
            soundEffectsError.setText("Wrong Input In Minutes Field!");
        }
        if(!this.soundEffectsSecondsReady)
        {
            soundEffectsError.setText("Wrong Input In Seconds Field!");
        }
        
        if((titleReady)&&
                (descriptionReady)&&
                  (archiveNumberReady)&&
                  (this.soundEffectsSecondsReady)&&
                    (this.soundEffectsMinutesReady))
        {
            trackOrganizer.addSoundEffect(soundEffectsTitle.getText(), soundEffectsMinutesVar, soundEffectsSecondsVar, soundEffectsDescription.getText(), soundEffectsArchiveNumberVar);
            soundEffectsError.setText("Sound Effects Added!" + " Title: " + soundEffectsTitle.getText());
            soundEffectsTitle.setText(null);
            soundEffectsMinutes.setText(null);
            soundEffectsSeconds.setText(null);
            soundEffectsDescription.setText(null);
            soundEffectsArchiveNumber.setText(null);
            
        }
        
    }//GEN-LAST:event_addSoundEffectsBtnActionPerformed

    /**
     * SoundEffects Medium Archive Number Field.
     * @param evt 
     */
    private void soundEffectsArchiveNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundEffectsArchiveNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundEffectsArchiveNumberActionPerformed

    /**
     * SoundEffects Seconds Field.
     * @param evt 
     */
    private void soundEffectsSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundEffectsSecondsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundEffectsSecondsActionPerformed

    /**
     * SoundEffect Minutes Field.
     * @param evt 
     */
    private void soundEffectsMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundEffectsMinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundEffectsMinutesActionPerformed

    /**
     * SoundEffect Title Field.
     * @param evt 
     */
    private void soundEffectsTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundEffectsTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundEffectsTitleActionPerformed

    /**
     * News Add News Button.
     * @param evt 
     */
    private void addNewsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewsBtnActionPerformed
        // TODO add your handling code here:
             
        System.out.println("Title: " + newsTitle.getText());
        System.out.println("Minutes: " + newsMinutesVar);
        System.out.println("Seconds: " + newsSecondsVar);
        System.out.println("Archive Number: " + newsArchiveNumberVar);
        System.out.println("Story: " + newsStory.getText());
        System.out.println("Journalist: " + newsJournalist.getText());
        System.out.println("Date Produced: " + newsDateProducedVar);
        System.out.println("Date Boardcasted: " + newsDateBoardcastedVar);
        
        
        
         boolean journalistReady = true;
         if(newsJournalist.getText().isEmpty())
         {
             newsError.setText("Error In Journalist Field!");
             journalistReady = false;
         }
         boolean storyReady = true;
         if(newsStory.getText().isEmpty())
         {
             newsError.setText("Error In Story Field!");
             storyReady = false;
         }
         boolean archiveNumberReady = true;
         if(newsArchiveNumber.getText().isEmpty())
         {
             newsError.setText("Error In Archive Number Field!");
             archiveNumberReady = false;
         }
         boolean titleReady = true;
         if(newsTitle.getText().isEmpty())
         {
             newsError.setText("Error In Title Field!");
             titleReady = false;
         }
         if(!this.newsMinutesReady)
         {
             newsError.setText("Wrong Input In Minutes Field!");
         }
         if(!this.newsSecondsReady)
         {
             newsError.setText("Wrong Input In Seconds Field!");
         }
         if(!this.newsDateProducedReady)
         {
             newsError.setText("Wrong Input In Date Produced Field!");
         }
         if(!this.newsDateBoardcastedReady)
         {
             newsError.setText("Wrong Input In Date Boardcasted Field!");
         }
        
         if((journalistReady)&&
                 (storyReady)&&
                  (archiveNumberReady)&&
                   (titleReady)&&
                    (this.newsMinutesReady)&&
                     (this.newsSecondsReady)&&
                      (this.newsDateProducedReady)&&
                        (this.newsDateBoardcastedReady))
         {
             trackOrganizer.addNewsTrack(newsTitle.getText(), newsMinutesVar, newsSecondsVar, newsArchiveNumberVar, newsStory.getText(), newsJournalist.getText(), newsDateProducedVar, newsDateBoardcastedVar);
             newsError.setText("News Added! " + " Title: " + newsTitle.getText());
             newsTitle.setText(null);
             newsMinutes.setText(null);
             newsSeconds.setText(null);
             newsArchiveNumber.setText(null);
             newsStory.setText(null);
             newsJournalist.setText(null);
             newsDateProduced.setText(null);
             newsDateBoardcasted.setText(null);
         }
 
    }//GEN-LAST:event_addNewsBtnActionPerformed

    /**
     * News Medium Archive Number Field.
     * @param evt 
     */
    private void newsArchiveNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsArchiveNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsArchiveNumberActionPerformed

    /**
     * News Date Boardcasted Field.
     * @param evt 
     */
    private void newsDateBoardcastedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsDateBoardcastedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsDateBoardcastedActionPerformed

    /**
     * News Date Produced Field.
     * @param evt 
     */
    private void newsDateProducedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsDateProducedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsDateProducedActionPerformed

    /**
     * News Journalist Field.
     * @param evt 
     */
    private void newsJournalistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsJournalistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsJournalistActionPerformed

    /**
     * News Story Field.
     * @param evt 
     */
    private void newsStoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsStoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsStoryActionPerformed

    /**
     * News Seconds Field.
     * @param evt 
     */
    private void newsSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsSecondsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsSecondsActionPerformed

    /**
     * News Minutes Field.
     * @param evt 
     */
    private void newsMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsMinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsMinutesActionPerformed

    /**
     * News Title Field.
     * @param evt 
     */
    private void newsTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsTitleActionPerformed

    private void musicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicBtnActionPerformed
        // TODO add your handling code here:
        musicFrame.setVisible(true);
        musicFrame.setSize(250, 450);
    }//GEN-LAST:event_musicBtnActionPerformed

    private void musicArchiveNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musicArchiveNumberKeyReleased
    try{
        musicError.setText(null);
        String tempString = musicArchiveNumber.getText();
        System.out.println(tempString);
        int tempInt = integer.parseInt(tempString);
        musicArchiveNumberVar = tempInt;
        if(trackOrganizer.getMediaAtArchiveNumber(musicArchiveNumberVar) == null)
            musicError.setText("No media at archive number!");
            
        }
        
        catch(NumberFormatException e)
        {
            musicError.setText("Error in Archive Number!");
            
        }
        
    }//GEN-LAST:event_musicArchiveNumberKeyReleased

    /**
     * Music Minutes Field.
     * @param evt 
     */
    private void musicMinutesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musicMinutesKeyReleased
        // TODO add your handling code here:
         try{
             musicError.setText(null);
        String tempString = musicMinutes.getText();
        int tempInt = integer.parseInt(tempString);
        musicMinutesVar = tempInt;
        this.musicMinutesReady = true;
        }
        catch(NumberFormatException e)
        {
            musicError.setText("Error in Minutes Field!");
            this.musicMinutesReady = false;
        }
            
    }//GEN-LAST:event_musicMinutesKeyReleased

    private void musicArchiveNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicArchiveNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musicArchiveNumberActionPerformed
/**
 * Music Seconds Field.
 * @param evt 
 */
    private void musicSecondsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musicSecondsKeyReleased
        // TODO add your handling code here:
        try{
            musicError.setText(null);
            String tempString = musicSeconds.getText();
            int tempInt = integer.parseInt(tempString);
            musicSecondsVar = tempInt;
            this.musicSecondsReady = true;
        }
        catch(NumberFormatException e)
        {
            musicError.setText("Error in seconds Field!");
            this.musicSecondsReady = false;
            
        }
    }//GEN-LAST:event_musicSecondsKeyReleased

    /**
     * Music Date Field.
     * @param evt 
     */
    private void musicDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musicDateKeyReleased
        // TODO add your handling code here:
        try{
            musicError.setText(null);
        String tempString = musicDate.getText();
        int tempInt = integer.parseInt(tempString);
        musicDateVar = tempInt;
        this.musicDateReady = true;
        }
        catch(NumberFormatException e)
        {
            musicError.setText("Error in Date Field!");
            this.musicDateReady = false;
        }
    }//GEN-LAST:event_musicDateKeyReleased

    /**
     * Music Times Played Field.
     * @param evt 
     */
    private void musicTimesPlayedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musicTimesPlayedKeyReleased
        // TODO add your handling code here:
        try{
            musicError.setText(null);
            String tempString = musicTimesPlayed.getText();
            int tempInt = integer.parseInt(tempString);
            musicTimesPlayedVar = tempInt;
            this.musicTimedPlayedReady = true;
        }
        catch(NumberFormatException e)
        {
            musicError.setText("Error in Times Played Field!");
            this.musicTimedPlayedReady = false;
        }
    }//GEN-LAST:event_musicTimesPlayedKeyReleased

    /**
     * Advertising Jingle Archive Number Field.
     * @param evt 
     */
    private void advertJingleArchiveNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_advertJingleArchiveNumberKeyReleased
        // TODO add your handling code here:
        try{
        advertJingleError.setText(null);
        String tempString = advertJingleArchiveNumber.getText();
        System.out.println(tempString);
        int tempInt = integer.parseInt(tempString);
        advertJingleArchiveNumberVar = tempInt;
        if(trackOrganizer.getMediaAtArchiveNumber(advertJingleArchiveNumberVar) == null)
            advertJingleError.setText("No Media At Archive Number!");
            
        }
        
        catch(NumberFormatException e)
        {
            advertJingleError.setText("Error in Archive Number!");
            
        }
    }//GEN-LAST:event_advertJingleArchiveNumberKeyReleased

    private void musicMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicMinutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musicMinutesActionPerformed

    /**
     * Advertising Jingle Minutes Field.
     * @param evt 
     */
    private void advertJingleMinutesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_advertJingleMinutesKeyReleased
        // TODO add your handling code here:
        try{
        advertJingleError.setText(null);
        String tempString = advertJingleMinutes.getText();
        int tempInt = integer.parseInt(tempString);
        advertJingleMinutesVar = tempInt;
        this.advertJingleMinutesReady = true;
        }
        catch(NumberFormatException e)
        {
            advertJingleError.setText("Error in Minutes Field!");
            this.advertJingleMinutesReady = false;
        }
    }//GEN-LAST:event_advertJingleMinutesKeyReleased

    /**
     * Advertising Jingle Frame Button.
     * @param evt 
     */
    private void advertisingJingleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertisingJingleBtnActionPerformed
        // TODO add your handling code here:
        advertisingJingleFrame.setVisible(true);
        advertisingJingleFrame.setSize(300, 400);
    }//GEN-LAST:event_advertisingJingleBtnActionPerformed

    private void advertJingleSecondsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_advertJingleSecondsKeyReleased
        // TODO add your handling code here:
        try{
        advertJingleError.setText(null);
        String tempString = advertJingleSeconds.getText();
        int tempInt = integer.parseInt(tempString);
        advertJingleSecondsVar = tempInt;
        this.advertJingleSecondsReady = true;
        }
        catch(NumberFormatException e)
        {
            advertJingleError.setText("Error in seconds Field!");
            this.advertJingleSecondsReady = false;
        }
    }//GEN-LAST:event_advertJingleSecondsKeyReleased

    /**
     * Sound Effects Seconds Field.
     * @param evt 
     */
    private void soundEffectsSecondsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soundEffectsSecondsKeyReleased
        // TODO add your handling code here:
        try{
        soundEffectsError.setText(null);
        String tempString = soundEffectsSeconds.getText();
        int tempInt = integer.parseInt(tempString);
        soundEffectsSecondsVar = tempInt;
        this.soundEffectsSecondsReady = true;
        }
        catch(NumberFormatException e)
        {
            soundEffectsError.setText("Error in seconds Field!");
            this.soundEffectsSecondsReady = false;
        }
    }//GEN-LAST:event_soundEffectsSecondsKeyReleased

    /**
     * Sound Effects Minutes Field.
     * @param evt 
     */
    private void soundEffectsMinutesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soundEffectsMinutesKeyReleased
        // TODO add your handling code here:
        try{
            soundEffectsError.setText(null);
        String tempString = soundEffectsMinutes.getText();
        int tempInt = integer.parseInt(tempString);
        soundEffectsMinutesVar = tempInt;
        this.soundEffectsMinutesReady = true;
        }
        catch(NumberFormatException e)
        {
            soundEffectsError.setText("Error in Minutes Field!");
            this.soundEffectsMinutesReady = false;
        }
    }//GEN-LAST:event_soundEffectsMinutesKeyReleased

    private void soundEffectsArchiveNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soundEffectsArchiveNumberKeyReleased
        // TODO add your handling code here:
        try{
        soundEffectsError.setText(null);
        String tempString = soundEffectsArchiveNumber.getText();
        System.out.println(tempString);
        int tempInt = integer.parseInt(tempString);
        soundEffectsArchiveNumberVar = tempInt;
        if(trackOrganizer.getMediaAtArchiveNumber(soundEffectsArchiveNumberVar) == null)
            soundEffectsError.setText("No Media At Archive Number!");
            
        }
        
        catch(NumberFormatException e)
        {
            soundEffectsError.setText("Error in Archive Number!");
            
        }
    }//GEN-LAST:event_soundEffectsArchiveNumberKeyReleased

    private void soundEffectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundEffectBtnActionPerformed
        // TODO add your handling code here:
        soundEffectsFrame.setVisible(true);
        soundEffectsFrame.setSize(250, 350);
    }//GEN-LAST:event_soundEffectBtnActionPerformed

    /**
     * News Minutes Field.
     * @param evt 
     */
    private void newsMinutesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newsMinutesKeyReleased
        // TODO add your handling code here:
          try{
        newsError.setText(null);
        String tempString = newsMinutes.getText();
        int tempInt = integer.parseInt(tempString);
        newsMinutesVar = tempInt;
        this.newsMinutesReady = true;
        }
        catch(NumberFormatException e)
        {
            newsError.setText("Error in Minutes Field!");
            this.newsMinutesReady = false;
        }
    }//GEN-LAST:event_newsMinutesKeyReleased

    /**
     * News Seconds Field.
     * @param evt 
     */
    private void newsSecondsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newsSecondsKeyReleased
        // TODO add your handling code here:
        try{
        newsError.setText(null);
        String tempString = newsSeconds.getText();
        int tempInt = integer.parseInt(tempString);
        newsSecondsVar = tempInt;
        this.newsSecondsReady = true;
        }
        catch(NumberFormatException e)
        {
            newsError.setText("Error in seconds Field!");
            this.newsSecondsReady = false;
        }
    }//GEN-LAST:event_newsSecondsKeyReleased

    /**
     * News Date Produced Field.
     * @param evt 
     */
    private void newsDateProducedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newsDateProducedKeyReleased
        // TODO add your handling code here:
        try{
        newsError.setText(null);
        String tempString = newsDateProduced.getText();
        int tempInt = integer.parseInt(tempString);
        newsDateProducedVar = tempInt;
        this.newsDateProducedReady = true;
        }
        catch(NumberFormatException e)
        {
            newsError.setText("Error in Date Produced Field!");
            this.newsDateProducedReady = false;
        }
    }//GEN-LAST:event_newsDateProducedKeyReleased

    /**
     * News Date Boardcasted Field.
     * @param evt 
     */
    private void newsDateBoardcastedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newsDateBoardcastedKeyReleased
        // TODO add your handling code here:
        try{
        newsError.setText(null);
        String tempString = newsDateBoardcasted.getText();
        int tempInt = integer.parseInt(tempString);
        newsDateBoardcastedVar = tempInt;
        this.newsDateBoardcastedReady = true;
        }
        catch(NumberFormatException e)
        {
            newsError.setText("Error in seconds Field!");
            this.newsDateBoardcastedReady = false;
        }
    }//GEN-LAST:event_newsDateBoardcastedKeyReleased

    /**
     * News Archive Number Field.
     * @param evt 
     */
    private void newsArchiveNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newsArchiveNumberKeyReleased
        // TODO add your handling code here:
        try{
        newsError.setText(null);
        String tempString = newsArchiveNumber.getText();
        System.out.println(tempString);
        int tempInt = integer.parseInt(tempString);
        newsArchiveNumberVar = tempInt;
        if(trackOrganizer.getMediaAtArchiveNumber(newsArchiveNumberVar) == null)
            newsError.setText("No Media At Archive Number!");
            
        }
        
        catch(NumberFormatException e)
        {
            newsError.setText("Error in Archive Number!");
            
        }
    }//GEN-LAST:event_newsArchiveNumberKeyReleased

    private void newsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsBtnActionPerformed
        // TODO add your handling code here:
        newsFrame.setVisible(true);
        newsFrame.setSize(300, 500);
    }//GEN-LAST:event_newsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAddTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAddTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAddTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAddTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAddTrack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdvertJingleBtn;
    private javax.swing.JButton addMusicBtn;
    private javax.swing.JButton addNewsBtn;
    private javax.swing.JButton addSoundEffectsBtn;
    private javax.swing.JTextField advertJingleArchiveNumber;
    private javax.swing.JTextField advertJingleCompany;
    private javax.swing.JLabel advertJingleError;
    private javax.swing.JTextField advertJingleMinutes;
    private javax.swing.JTextField advertJingleProduct;
    private javax.swing.JTextField advertJingleSeconds;
    private javax.swing.JTextField advertJingleTitle;
    private javax.swing.JButton advertisingJingleBtn;
    private javax.swing.JFrame advertisingJingleFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField musicArchiveNumber;
    private javax.swing.JTextField musicArtist;
    private javax.swing.JButton musicBtn;
    private javax.swing.JTextField musicDate;
    private javax.swing.JLabel musicError;
    private javax.swing.JFrame musicFrame;
    private javax.swing.JTextField musicMinutes;
    private javax.swing.JTextField musicSeconds;
    private javax.swing.JTextField musicTimesPlayed;
    private javax.swing.JTextField musicTitle;
    private javax.swing.JTextField newsArchiveNumber;
    private javax.swing.JButton newsBtn;
    private javax.swing.JTextField newsDateBoardcasted;
    private javax.swing.JTextField newsDateProduced;
    private javax.swing.JLabel newsError;
    private javax.swing.JFrame newsFrame;
    private javax.swing.JTextField newsJournalist;
    private javax.swing.JTextField newsMinutes;
    private javax.swing.JTextField newsSeconds;
    private javax.swing.JTextField newsStory;
    private javax.swing.JTextField newsTitle;
    private javax.swing.JButton soundEffectBtn;
    private javax.swing.JTextField soundEffectsArchiveNumber;
    private javax.swing.JTextField soundEffectsDescription;
    private javax.swing.JLabel soundEffectsError;
    private javax.swing.JFrame soundEffectsFrame;
    private javax.swing.JTextField soundEffectsMinutes;
    private javax.swing.JTextField soundEffectsSeconds;
    private javax.swing.JTextField soundEffectsTitle;
    // End of variables declaration//GEN-END:variables
}
