
import javax.swing.JTable;
import javax.swing.Popup;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Olav Rune
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    TrackOrganizer trackOrganizer;
 
    
    public MainFrame() {
        trackOrganizer = new TrackOrganizer();
        initComponents();
        addMediumPanel.setVisible(false);
        list.setVisible(false);
        
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMedium = new javax.swing.JButton();
        addMediumPanel = new javax.swing.JPanel();
        listCDArchive = new javax.swing.JButton();
        listArchive = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        CDlist = new javax.swing.JTable();
        addTrack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addMedium.setText("New Medium");
        addMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMediumActionPerformed(evt);
            }
        });

        listCDArchive.setText("List CD archive");
        listCDArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCDArchiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addMediumPanelLayout = new javax.swing.GroupLayout(addMediumPanel);
        addMediumPanel.setLayout(addMediumPanelLayout);
        addMediumPanelLayout.setHorizontalGroup(
            addMediumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMediumPanelLayout.createSequentialGroup()
                .addComponent(listCDArchive)
                .addGap(0, 36, Short.MAX_VALUE))
        );
        addMediumPanelLayout.setVerticalGroup(
            addMediumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMediumPanelLayout.createSequentialGroup()
                .addComponent(listCDArchive)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        listArchive.setText("List all tracks");
        listArchive.setToolTipText("");
        listArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listArchiveActionPerformed(evt);
            }
        });

        list.setModel(new MusicTableModel(trackOrganizer)
        );
        jScrollPane1.setViewportView(list);

        jTabbedPane1.addTab("Music Tracks", jScrollPane1);

        CDlist.setModel(new CDTableModel(trackOrganizer)
        );
        jScrollPane2.setViewportView(CDlist);

        jTabbedPane1.addTab("Albums", jScrollPane2);

        addTrack.setText("New Track");
        addTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addMedium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addTrack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addMediumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listArchive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMedium)
                    .addComponent(listArchive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addMediumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTrack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMediumActionPerformed
       //addMediumPanel.setVisible(true);
        FrameAddMedium mediumFrame = new FrameAddMedium();
        mediumFrame.setInputParameter(trackOrganizer);
        mediumFrame.setVisible(true);
        
        
    }//GEN-LAST:event_addMediumActionPerformed

    private void addTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrackActionPerformed

       // PopUp dialog = new PopUp(this, true);
       // dialog.setVisible(true);
        FrameAddTrack trackFrame = new FrameAddTrack();
        trackFrame.setInputParameter(trackOrganizer);
        trackFrame.setVisible(true);
            

    }//GEN-LAST:event_addTrackActionPerformed

    private void listArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listArchiveActionPerformed
        // TODO add your handling code here:
       list.setVisible(true);
    
       

        
        
      
    }//GEN-LAST:event_listArchiveActionPerformed

    private void listCDArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCDArchiveActionPerformed
        // TODO add your handling code here:
        CDlist.setVisible(true);
    }//GEN-LAST:event_listCDArchiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CDlist;
    private javax.swing.JButton addMedium;
    private javax.swing.JPanel addMediumPanel;
    private javax.swing.JButton addTrack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable list;
    private javax.swing.JButton listArchive;
    private javax.swing.JButton listCDArchive;
    // End of variables declaration//GEN-END:variables
}
